#!/bin/sh

. /lib/functions/uci-defaults.sh

uci set system.config.enable_usb3_support='0'

if [ $(uci get env.rip.sw_flag) = "F2" ]; then
  uci delete system.ntp.server
  uci add_list system.ntp.server='ntp.internode.on.net'
fi

uci commit system
